// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace AquariumTracker.Models
{
    public partial class AquariumOwnerListView
    {
        public int AquariumId { get; set; }
        public string AquariumName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}